# Generated by Django 5.2.9 on 2026-03-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chai_varity',
            new_name='CHAIVARIETY',
        ),
    ]
