# Generated by Django 5.2.9 on 2026-03-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_rename_chai_varity_chaivariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='descriptions',
            field=models.TextField(default='empty'),
        ),
    ]
