# Generated by Django 5.2.9 on 2026-03-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default='10'),
        ),
    ]
